### ISSUE TITLE
Integrating woocommerce

### ISSUE THREAD

**Issue by andrewkoung** [vercel/commerce-framework#2]
Hi! 

My friend took in an interest on wanting to use this project, but there's only support for BigCommerce. He recommended that I could try to find a way to integrate WooCommerce. Is there any advice on how I can get started?

**Comment by heydluv** [comment]
@andrewkoung I had the same question and I found [this thread](https://github.com/vercel/commerce/issues/2) to be helpful.

**Comment by andrewkoung** [comment]
@heydluv Thank you! I was wondering if you had any idea on how custom data hooks for different commerce could be tested? I noticed that vercel/commerce dependencies target "@bigcommerce/storefront-data-hooks/....".

**Comment by leerob** [comment]
Hey there! Thanks for raising this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: [#966](https://github.com/vercel/commerce/pull/966)
